version: 43.0.9
pageUuid: 1ede9fe0-6009-11ea-807f-2fea906f13de
appTemplate:
  isFetching: false
  plugins:
    ordered:
      - query1:
          pluginTemplate:
            id: query1
            type: datasource
            subtype: SqlQuery
            resourceName: onprem-db
            template:
              ordered:
                - queryRefreshTime: ''
                - databasePasswordOverride: ''
                - queryDisabledMessage: ''
                - successMessage: ''
                - queryDisabled: ''
                - playgroundQuerySaveId: 0
                - resourceNameOverride: ''
                - runWhenModelUpdates: true
                - query: 'select id, email, "firstName" from users limit 10'
                - playgroundQueryUuid: ''
                - playgroundQueryId: 0
                - privateParams: []
                - triggersOnSuccess: []
                - runWhenPageLoadsDelay: ''
                - warningCodes: []
                - data: null
                - importedQueryInputs:
                    ordered: []
                - showSuccessConfetti: false
                - isImported: false
                - showSuccessToaster: true
                - dataArray: []
                - cacheKeyTtl: ''
                - triggersOnFailure: []
                - databaseNameOverride: ''
                - confirmationMessage: null
                - isFetching: false
                - rawData: null
                - queryTriggerDelay: '0'
                - watchedParams: []
                - timestamp: 0
                - importedQueryDefaults:
                    ordered: []
                - enableTransformer: false
                - runWhenPageLoads: false
                - transformer: >-
                    // type your code here

                    // example: return formatDataAsArray(data).filter(row =>
                    row.quantity > 20)

                    return data
                - queryTimeout: '10001'
                - requireConfirmation: false
                - enableCaching: false
                - databaseUsernameOverride: ''
                - shouldEnableBatchQuerying: false
                - queryThrottleTime: '750'
            createdAt: 2020-03-07T00:18:13.020Z
            updatedAt: 2020-03-07T01:02:32.981Z
      - table1:
          pluginTemplate:
            id: table1
            type: widget
            subtype: TableWidget
            template:
              ordered:
                - sortMappedValue:
                    ordered: []
                - normalizedData: null
                - columnWidths: []
                - columnWidthsMobile: []
                - columnTypeSpecificExtras:
                    ordered: []
                - onRowAdded: ''
                - columnHeaderNames:
                    ordered: []
                - alwaysShowPaginator: false
                - columnColors:
                    ordered:
                      - googleToken: ''
                      - lastName: ''
                      - enabled: ''
                      - credits_used: ''
                      - market_tier: ''
                      - address_id: ''
                      - profilePhotoUrl: ''
                      - active: ''
                      - hashedPassword: ''
                      - resetPasswordExpires: ''
                      - sales_rep: ''
                      - name: ''
                      - sales: ''
                      - company_name: ''
                      - mrr: ''
                      - sid: ''
                      - organizationId: ''
                      - updatedAt: ''
                      - resetPasswordToken: ''
                      - activebool: ''
                      - records_validated: ''
                      - credits_remaining: ''
                      - create_date: ''
                      - last_update: ''
                      - contract_length: ''
                      - twoFactorAuthSecret: ''
                      - googleId: ''
                      - last_name: ''
                      - records_expected: ''
                      - userName: ''
                      - store_id: ''
                      - first_name: ''
                      - id: ''
                      - createdAt: ''
                      - firstName: ''
                      - customer_id: ''
                      - lastActive: ''
                      - email: ''
                      - csm: ''
                      - pm: ''
                      - lastLoggedIn: ''
                      - twoFactorAuthEnabled: ''
                - allowMultiRowSelect: false
                - columnFormats:
                    ordered: []
                - showFilterButton: true
                - nextBeforeCursor: ''
                - columnVisibility:
                    ordered:
                      - googleToken: true
                      - lastName: true
                      - enabled: true
                      - credits_used: false
                      - market_tier: false
                      - address_id: true
                      - profilePhotoUrl: true
                      - active: true
                      - hashedPassword: true
                      - resetPasswordExpires: true
                      - sales_rep: false
                      - name: true
                      - Sales: true
                      - sales: true
                      - company_name: false
                      - mrr: false
                      - sid: true
                      - organizationId: true
                      - updatedAt: true
                      - resetPasswordToken: true
                      - activebool: true
                      - records_validated: false
                      - credits_remaining: false
                      - create_date: true
                      - last_update: true
                      - contract_length: false
                      - twoFactorAuthSecret: true
                      - googleId: true
                      - last_name: true
                      - records_expected: false
                      - userName: true
                      - Title: true
                      - store_id: true
                      - first_name: true
                      - id: true
                      - createdAt: true
                      - firstName: 'true'
                      - customer_id: true
                      - lastActive: true
                      - email: true
                      - Description: true
                      - csm: false
                      - pm: false
                      - lastLoggedIn: true
                      - twoFactorAuthEnabled: true
                - selectedPageIndex: '0'
                - actionButtonColumnName: Actions
                - filterStackType: and
                - downloadRawData: false
                - showFetchingIndicator: true
                - serverPaginated: false
                - data: '{{query1.data}}'
                - displayedData: null
                - actionButtons: []
                - actionButtonSelectsRow: true
                - selectRowByDefault: true
                - defaultSortByColumn: ''
                - paginationOffset: 0
                - sortedDesc: false
                - columnMappersRenderAsHTML:
                    ordered: []
                - pageSize: 14
                - useDynamicColumnSettings: true
                - actionButtonPosition: left
                - bulkUpdateAction: ''
                - afterCursor: ''
                - changeSet:
                    object: {}
                - sortedColumn: ''
                - columnAllowOverflow:
                    ordered: []
                - beforeCursor: ''
                - serverPaginationType: limitOffsetBased
                - onRowSelect: ''
                - showDownloadButton: true
                - selectedIndex: ''
                - defaultSortDescending: false
                - dynamicColumnSettings: '[ "column1": { "name": "column2", "type": "integer" } ]'
                - totalRowCount: ''
                - recordUpdates:
                    array: []
                - newRow: null
                - columnEditable:
                    ordered: []
                - filters:
                    array: []
                - displayedDataIndices: null
                - columnMappers:
                    ordered: []
                - showClearSelection: false
                - selectedCell:
                    object:
                      index: null
                      data: null
                      columnName: null
                - columns:
                    - Title
                    - Description
                    - Sales
                    - id
                    - name
                    - email
                    - sales
                    - customer_id
                    - store_id
                    - first_name
                    - last_name
                    - address_id
                    - activebool
                    - create_date
                    - last_update
                    - active
                    - company_name
                    - credits_used
                    - credits_remaining
                    - records_validated
                    - records_expected
                    - sales_rep
                    - csm
                    - pm
                    - market_tier
                    - contract_length
                    - mrr
                    - firstName
                    - lastName
                    - profilePhotoUrl
                    - googleId
                    - googleToken
                    - hashedPassword
                    - organizationId
                    - createdAt
                    - updatedAt
                    - lastLoggedIn
                    - enabled
                    - resetPasswordToken
                    - resetPasswordExpires
                    - sid
                    - userName
                    - twoFactorAuthSecret
                    - twoFactorAuthEnabled
                    - lastActive
                - sort: null
                - calculatedColumns: []
                - selectedRow:
                    object:
                      index: null
                      data: null
                - showPaginationOnTop: false
                - nextAfterCursor: ''
                - useCompactMode: true
            position2:
              position2:
                height: 10
                width: 12
            createdAt: 2020-03-07T00:18:19.284Z
            updatedAt: 2020-03-07T01:11:35.573Z
      - table2:
          pluginTemplate:
            id: table2
            type: widget
            subtype: TableWidget
            template:
              ordered:
                - sortMappedValue:
                    ordered: []
                - normalizedData: null
                - columnWidths: []
                - columnWidthsMobile: []
                - columnTypeSpecificExtras:
                    ordered: []
                - onRowAdded: ''
                - columnHeaderNames:
                    ordered: []
                - alwaysShowPaginator: false
                - columnColors:
                    ordered:
                      - googleToken: ''
                      - lastName: ''
                      - enabled: ''
                      - credits_used: ''
                      - market_tier: ''
                      - address_id: ''
                      - profilePhotoUrl: ''
                      - active: ''
                      - hashedPassword: ''
                      - resetPasswordExpires: ''
                      - sales_rep: ''
                      - company_name: ''
                      - mrr: ''
                      - sid: ''
                      - organizationId: ''
                      - updatedAt: ''
                      - resetPasswordToken: ''
                      - activebool: ''
                      - records_validated: ''
                      - credits_remaining: ''
                      - create_date: ''
                      - last_update: ''
                      - contract_length: ''
                      - twoFactorAuthSecret: ''
                      - googleId: ''
                      - last_name: ''
                      - records_expected: ''
                      - userName: ''
                      - store_id: ''
                      - first_name: ''
                      - id: ''
                      - createdAt: ''
                      - firstName: ''
                      - customer_id: ''
                      - lastActive: ''
                      - email: ''
                      - csm: ''
                      - pm: ''
                      - lastLoggedIn: ''
                      - twoFactorAuthEnabled: ''
                - allowMultiRowSelect: false
                - columnFormats:
                    ordered: []
                - showFilterButton: true
                - nextBeforeCursor: ''
                - columnVisibility:
                    ordered:
                      - googleToken: true
                      - lastName: true
                      - enabled: true
                      - credits_used: true
                      - market_tier: true
                      - address_id: true
                      - profilePhotoUrl: true
                      - active: true
                      - hashedPassword: true
                      - resetPasswordExpires: true
                      - sales_rep: true
                      - Sales: true
                      - company_name: true
                      - mrr: true
                      - sid: true
                      - organizationId: true
                      - updatedAt: true
                      - resetPasswordToken: true
                      - activebool: true
                      - records_validated: true
                      - credits_remaining: true
                      - create_date: true
                      - last_update: true
                      - contract_length: true
                      - twoFactorAuthSecret: true
                      - googleId: true
                      - last_name: true
                      - records_expected: true
                      - userName: true
                      - Title: true
                      - store_id: true
                      - first_name: true
                      - id: true
                      - createdAt: true
                      - firstName: true
                      - customer_id: true
                      - lastActive: true
                      - email: true
                      - Description: true
                      - csm: true
                      - pm: true
                      - lastLoggedIn: true
                      - twoFactorAuthEnabled: true
                - selectedPageIndex: '0'
                - actionButtonColumnName: Actions
                - filterStackType: and
                - downloadRawData: false
                - showFetchingIndicator: true
                - serverPaginated: false
                - data: '{{ query1.data }}'
                - displayedData: null
                - actionButtons: []
                - actionButtonSelectsRow: true
                - selectRowByDefault: true
                - defaultSortByColumn: ''
                - paginationOffset: 0
                - sortedDesc: false
                - columnMappersRenderAsHTML:
                    ordered: []
                - pageSize: 6
                - useDynamicColumnSettings: false
                - actionButtonPosition: left
                - bulkUpdateAction: ''
                - afterCursor: ''
                - changeSet:
                    object: {}
                - sortedColumn: ''
                - columnAllowOverflow:
                    ordered: []
                - beforeCursor: ''
                - serverPaginationType: limitOffsetBased
                - onRowSelect: ''
                - showDownloadButton: true
                - selectedIndex: ''
                - defaultSortDescending: false
                - dynamicColumnSettings: null
                - totalRowCount: ''
                - recordUpdates:
                    array: []
                - newRow: null
                - columnEditable:
                    ordered: []
                - filters:
                    array: []
                - displayedDataIndices: null
                - columnMappers:
                    ordered: []
                - showClearSelection: false
                - selectedCell:
                    object:
                      index: null
                      data: null
                      columnName: null
                - columns:
                    - Title
                    - Description
                    - Sales
                    - customer_id
                    - store_id
                    - first_name
                    - last_name
                    - email
                    - address_id
                    - activebool
                    - create_date
                    - last_update
                    - active
                    - company_name
                    - credits_used
                    - credits_remaining
                    - records_validated
                    - records_expected
                    - sales_rep
                    - csm
                    - pm
                    - market_tier
                    - contract_length
                    - mrr
                    - id
                    - firstName
                    - lastName
                    - profilePhotoUrl
                    - googleId
                    - googleToken
                    - hashedPassword
                    - organizationId
                    - createdAt
                    - updatedAt
                    - lastLoggedIn
                    - enabled
                    - resetPasswordToken
                    - resetPasswordExpires
                    - sid
                    - userName
                    - twoFactorAuthSecret
                    - twoFactorAuthEnabled
                    - lastActive
                - sort: null
                - calculatedColumns: []
                - selectedRow:
                    object:
                      index: null
                      data: null
                - showPaginationOnTop: false
                - nextAfterCursor: ''
                - useCompactMode: false
            position2:
              position2:
                row: 11
                height: 8
                width: 8
            createdAt: 2020-03-07T00:44:37.400Z
            updatedAt: 2020-03-07T00:52:11.280Z
  createdAt: null
  version: 2.54.11
  responsiveLayoutDisabled: false
  urlFragmentDefinitions: []
  pageLoadValueOverrides: []
